name: Gthub portfolio_release_1

on: [push] # Triggers the workflow on any push event

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest # Job runs on a fresh Ubuntu Linux runner
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Uses the actions/checkout action to clone the repo

      - name: Run a one-line script
        run: echo "🎉 Hello, world! This job is running on ${{ runner.os }}." # Runs a single line command

      - name: List files in the repository
        run: | # Use multiline command to list files in the workspace
          ls ${{ github.workspace }}
          echo "🍏 This job's status is ${{ job.status }}."
